In [ ]:
!pip install torch torchaudio -q
!pip install pyannote.audio -q
!pip install silero-vad -q
!pip install soundfile pandas -q

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.8/44.8 kB 3.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.5/79.5 kB 8.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 59.6/59.6 kB 6.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 893.7/893.7 kB 33.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 853.6/853.6 kB 65.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.1/72.1 kB 8.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 180.2/180.2 kB 21.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 69.0/69.0 kB 8.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 231.6/231.6 kB 22.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.5/57.5 kB 6.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 53.7/53.7 kB 6.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.7/49.7 kB 5.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.8/127.8 kB 17.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 48.5/48.5 kB 5.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 983.4/983.4 kB 73.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.6/16.6 MB 106.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 419.5/419.5 kB 44.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.9/10.9 MB 122.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 857.3/857.3 kB 67.0 MB/s eta 0:00:00
  Building wheel for julius (setup.py) ... done
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires pandas==2.2.2, but you have pandas 3.0.2 which is incompatible.
bqplot 0.12.45 requires pandas<3.0.0,>=1.0.0, but you have pandas 3.0.2 which is incompatible.
dask-cudf-cu12 26.2.1 requires pandas<2.4.0,>=2.0, but you have pandas 3.0.2 which is incompatible.
numba 0.60.0 requires numpy<2.1,>=1.22, but you have numpy 2.4.4 which is incompatible.
cudf-cu12 26.2.1 requires pandas<2.4.0,>=2.0, but you have pandas 3.0.2 which is incompatible.
google-adk 1.28.0 requires opentelemetry-api<1.39.0,>=1.36.0, but you have opentelemetry-api 1.41.0 which is incompatible.
google-adk 1.28.0 requires opentelemetry-sdk<1.39.0,>=1.36.0, but you have opentelemetry-sdk 1.41.0 which is incompatible.
gradio 5.50.0 requires pandas<3.0,>=1.0, but you have pandas 3.0.2 which is incompatible.
db-dtypes 1.5.1 requires pandas<3.0.0,>=1.5.3, but you have pandas 3.0.2 which is incompatible.
opentelemetry-exporter-gcp-logging 1.11.0a0 requires opentelemetry-sdk<1.39.0,>=1.35.0, but you have opentelemetry-sdk 1.41.0 which is incompatible.
tensorflow 2.19.0 requires numpy<2.2.0,>=1.26.0, but you have numpy 2.4.4 which is incompatible.
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.1/9.1 MB 95.3 MB/s eta 0:00:00

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving audio-1775052030.webm to audio-1775052030.webm
Saving audio-1775052060.webm to audio-1775052060.webm
Saving audio-1775052090.webm to audio-1775052090.webm
Saving audio-1775052120.webm to audio-1775052120.webm
Saving audio-1775052150.webm to audio-1775052150.webm
Saving audio-1775052180.webm to audio-1775052180.webm
Saving audio-1775052210.webm to audio-1775052210.webm
Saving audio-1775052240.webm to audio-1775052240.webm
Saving audio-1775052270.webm to audio-1775052270.webm
Saving audio-1775052300.webm to audio-1775052300.webm
Saving audio-1775052330.webm to audio-1775052330.webm
Saving audio-1775052360.webm to audio-1775052360.webm
Saving audio-1775052390.webm to audio-1775052390.webm
Saving audio-1775052420.webm to audio-1775052420.webm
Saving audio-1775052450.webm to audio-1775052450.webm
Saving audio-1775052480.webm to audio-1775052480.webm
Saving audio-1775052510.webm to audio-1775052510.webm
Saving audio-1775052540.webm to audio-1775052540.webm
Saving audio-1775052570.webm to audio-1775052570.webm
Saving audio-1775052600.webm to audio-1775052600.webm
Saving audio-1775052630.webm to audio-1775052630.webm
Saving audio-1775052660.webm to audio-1775052660.webm
Saving audio-1775052690.webm to audio-1775052690.webm
Saving audio-1775052720.webm to audio-1775052720.webm
Saving audio-1775053176.webm to audio-1775053176.webm
Saving audio-1775053236.webm to audio-1775053236.webm
Saving audio-1775053266.webm to audio-1775053266.webm
Saving audio-1775053326.webm to audio-1775053326.webm
Saving audio-1775053416.webm to audio-1775053416.webm
Saving audio-1775053561.webm to audio-1775053561.webm
Saving audio-1775053621.webm to audio-1775053621.webm
Saving audio-1775053741.webm to audio-1775053741.webm
Saving audio-1775054148.webm to audio-1775054148.webm
Saving audio-1775054178.webm to audio-1775054178.webm
Saving audio-1775054208.webm to audio-1775054208.webm
Saving audio-1775054238.webm to audio-1775054238.webm
Saving audio-1775054268.webm to audio-1775054268.webm
Saving audio-1775054298.webm to audio-1775054298.webm
Saving audio-1775054328.webm to audio-1775054328.webm
Saving audio-1775054357.webm to audio-1775054357.webm
Saving audio-1775054358.webm to audio-1775054358.webm
Saving audio-1775054387.webm to audio-1775054387.webm
Saving audio-1775054388.webm to audio-1775054388.webm
Saving audio-1775054418.webm to audio-1775054418.webm
Saving audio-1775054448.webm to audio-1775054448.webm
Saving audio-1775054478.webm to audio-1775054478.webm
Saving audio-1775054508.webm to audio-1775054508.webm
Saving audio-1775054538.webm to audio-1775054538.webm
Saving audio-1775054568.webm to audio-1775054568.webm
Saving audio-1775054598.webm to audio-1775054598.webm
Saving audio-1775054627.webm to audio-1775054627.webm
Saving audio-1775054628.webm to audio-1775054628.webm
Saving audio-1775054658.webm to audio-1775054658.webm
Saving audio-1775054688.webm to audio-1775054688.webm
Saving audio-1775054718.webm to audio-1775054718.webm
Saving audio-1775054748.webm to audio-1775054748.webm
Saving audio-1775054778.webm to audio-1775054778.webm
Saving audio-1775054808.webm to audio-1775054808.webm
Saving audio-1775054838.webm to audio-1775054838.webm
Saving audio-1775054868.webm to audio-1775054868.webm
Saving audio-1775054898.webm to audio-1775054898.webm
Saving audio-1775054928.webm to audio-1775054928.webm
Saving audio-1775054958.webm to audio-1775054958.webm
Saving audio-1775054988 (1).webm to audio-1775054988 (1).webm
Saving audio-1775054988.webm to audio-1775054988.webm
Saving audio-1775055018.webm to audio-1775055018.webm
Saving audio-1775055048.webm to audio-1775055048.webm
Saving audio-1775055077.webm to audio-1775055077.webm
Saving audio-1775055078.webm to audio-1775055078.webm
Saving audio-1775055107.webm to audio-1775055107.webm
Saving audio-1775055108.webm to audio-1775055108.webm
Saving audio-1775055138.webm to audio-1775055138.webm
Saving audio-1775055198.webm to audio-1775055198.webm
Saving audio-1775055258.webm to audio-1775055258.webm
Saving audio-1775055317.webm to audio-1775055317.webm
Saving audio-1775055347.webm to audio-1775055347.webm
Saving audio-1775055377.webm to audio-1775055377.webm
Saving audio-1775055407.webm to audio-1775055407.webm
Saving audio-1775055437.webm to audio-1775055437.webm
Saving audio-1775055467.webm to audio-1775055467.webm
Saving audio-1775055497.webm to audio-1775055497.webm
Saving audio-1775055587.webm to audio-1775055587.webm
Saving audio-1775055677.webm to audio-1775055677.webm
Saving audio-1775055707.webm to audio-1775055707.webm
Saving audio-1775055737.webm to audio-1775055737.webm
Saving audio-1775055887.webm to audio-1775055887.webm
Saving audio-1775055947.webm to audio-1775055947.webm
Saving audio-1775056127.webm to audio-1775056127.webm
Saving audio-1775056217.webm to audio-1775056217.webm
Saving audio-1775056247.webm to audio-1775056247.webm
Saving audio-1775056337.webm to audio-1775056337.webm
Saving audio-1775056367.webm to audio-1775056367.webm
Saving audio-1775056487.webm to audio-1775056487.webm

In [ ]:
import os, time, tempfile
import torch, torchaudio, pandas as pd
from pyannote.audio import Pipeline
from silero_vad import load_silero_vad, get_speech_timestamps

In [ ]:
audio_files = [f for f in uploaded.keys() if f.lower().endswith(('.wav','.mp3','.webm','.m4a'))]
print("Total files:", len(audio_files))

Total files: 93

In [ ]:
device_used = "cuda" if torch.cuda.is_available() else "cpu"
print("Device:", device_used)

Device: cuda

In [ ]:
silero_model = load_silero_vad()
print("Silero loaded")

Silero loaded

In [ ]:
HF_TOKEN = "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"

pyannote_pipeline = Pipeline.from_pretrained(
    "pyannote/speaker-diarization-community-1",
    token=HF_TOKEN
)

pyannote_pipeline.to(torch.device(device_used))
print("Pyannote loaded")

config.yaml:   0%|          | 0.00/444 [00:00<?, ?B/s]

segmentation/pytorch_model.bin:   0%|          | 0.00/5.91M [00:00<?, ?B/s]

plda/xvec_transform.npz:   0%|          | 0.00/134k [00:00<?, ?B/s]

plda/plda.npz:   0%|          | 0.00/134k [00:00<?, ?B/s]

embedding/pytorch_model.bin:   0%|          | 0.00/26.6M [00:00<?, ?B/s]

Pyannote loaded

In [ ]:
def load_audio_mono_16k(file_path):
    waveform, sample_rate = torchaudio.load(file_path)

    if waveform.shape[0] > 1:
        waveform = torch.mean(waveform, dim=0, keepdim=True)

    if sample_rate != 16000:
        resampler = torchaudio.transforms.Resample(
            orig_freq=sample_rate,
            new_freq=16000
        )
        waveform = resampler(waveform)
        sample_rate = 16000

    return waveform, sample_rate

In [ ]:
def apply_silero_vad_to_file(file_path, threshold=0.5, min_speech_duration_ms=250):
    waveform, sample_rate = load_audio_mono_16k(file_path)

    speech_timestamps = get_speech_timestamps(
        waveform.squeeze(0),
        silero_model,
        sampling_rate=sample_rate,
        threshold=threshold,
        min_speech_duration_ms=min_speech_duration_ms
    )

    return waveform, sample_rate, speech_timestamps

In [ ]:
def save_speech_only_audio(waveform, speech_timestamps, sample_rate):
    if len(speech_timestamps) == 0:
        return None, 0.0

    chunks = []
    total_speech_sec = 0.0

    for seg in speech_timestamps:
        start = seg["start"]
        end = seg["end"]
        chunks.append(waveform[:, start:end])
        total_speech_sec += (end - start) / sample_rate

    speech_waveform = torch.cat(chunks, dim=1)

    tmp_file = tempfile.NamedTemporaryFile(suffix=".wav", delete=False)
    temp_path = tmp_file.name
    tmp_file.close()

    torchaudio.save(temp_path, speech_waveform, sample_rate)

    return temp_path, total_speech_sec

In [ ]:
def diarize_speech_file(temp_audio_path):
    result = pyannote_pipeline(temp_audio_path)

    if hasattr(result, "itertracks"):
        diarization = result
    elif hasattr(result, "speaker_diarization"):
        diarization = result.speaker_diarization
    elif hasattr(result, "exclusive_speaker_diarization"):
        diarization = result.exclusive_speaker_diarization
    else:
        raise TypeError(
            f"Unsupported diarization output type: {type(result)}. "
            f"Available attributes: {dir(result)}"
        )

    speakers = set()
    for turn, _, speaker in diarization.itertracks(yield_label=True):
        speakers.add(speaker)

    return diarization, len(speakers)

In [ ]:
test_file = audio_files[0]
print("Testing file:", test_file)

waveform, sr, speech_timestamps = apply_silero_vad_to_file(
    test_file,
    threshold=0.5,
    min_speech_duration_ms=250
)

print("Speech segments found:", len(speech_timestamps))

temp_audio_path, total_speech_sec = save_speech_only_audio(
    waveform,
    speech_timestamps,
    sr
)

if temp_audio_path is None:
    print("No speech detected")
else:
    diarization, num_speakers = diarize_speech_file(temp_audio_path)
    print("Total speech duration:", round(total_speech_sec, 2), "sec")
    print("Predicted speakers:", num_speakers)

    os.remove(temp_audio_path)

Testing file: audio-1775052030.webm
Speech segments found: 2
Total speech duration: 20.31 sec
Predicted speakers: 1

In [ ]:
results = []

model_name = "SileroVAD + Pyannote"

for file_name in audio_files:
    temp_audio_path = None

    try:
        start_time = time.time()

        waveform, sr = load_audio_mono_16k(file_name)
        duration = waveform.shape[1] / sr

        waveform, sr, speech_timestamps = apply_silero_vad_to_file(
            file_path=file_name,
            threshold=0.5,
            min_speech_duration_ms=250
        )

        temp_audio_path, total_speech_sec = save_speech_only_audio(
            waveform=waveform,
            speech_timestamps=speech_timestamps,
            sample_rate=sr
        )

        if temp_audio_path is None:
            num_speakers = 0
        else:
            diarization, num_speakers = diarize_speech_file(temp_audio_path)

        end_time = time.time()
        processing_time = end_time - start_time

        results.append({
            "file_name": file_name,
            "duration": round(duration, 2),
            "model_name": model_name,
            "device_used": device_used,
            "number_of_speakers": int(num_speakers),
            "processing_time_sec": round(processing_time, 2),
            "human_verification_speaker": None
        })

        print(f"{file_name} -> speakers={num_speakers}")

    except Exception as e:
        results.append({
            "file_name": file_name,
            "duration": None,
            "model_name": model_name,
            "device_used": device_used,
            "number_of_speakers": None,
            "processing_time_sec": None,
            "human_verification_speaker": None,
            "error": str(e)
        })

        print(f"Error on {file_name}: {e}")

    finally:
        if temp_audio_path is not None and os.path.exists(temp_audio_path):
            os.remove(temp_audio_path)

audio-1775052030.webm -> speakers=1
audio-1775052060.webm -> speakers=0
audio-1775052090.webm -> speakers=0
audio-1775052120.webm -> speakers=1
audio-1775052150.webm -> speakers=1
audio-1775052180.webm -> speakers=1
audio-1775052210.webm -> speakers=1
audio-1775052240.webm -> speakers=1
audio-1775052270.webm -> speakers=1
audio-1775052300.webm -> speakers=1
audio-1775052330.webm -> speakers=1
audio-1775052360.webm -> speakers=2
audio-1775052390.webm -> speakers=1
audio-1775052420.webm -> speakers=1
audio-1775052450.webm -> speakers=1
audio-1775052480.webm -> speakers=1
audio-1775052510.webm -> speakers=1
audio-1775052540.webm -> speakers=1
audio-1775052570.webm -> speakers=2
audio-1775052600.webm -> speakers=1
audio-1775052630.webm -> speakers=1
audio-1775052660.webm -> speakers=1
audio-1775052690.webm -> speakers=1
audio-1775052720.webm -> speakers=1
audio-1775053176.webm -> speakers=0
audio-1775053236.webm -> speakers=0
audio-1775053266.webm -> speakers=0
audio-1775053326.webm -> speakers=0
audio-1775053416.webm -> speakers=0
audio-1775053561.webm -> speakers=0
audio-1775053621.webm -> speakers=0
audio-1775053741.webm -> speakers=0
audio-1775054148.webm -> speakers=0
audio-1775054178.webm -> speakers=0

/usr/local/lib/python3.12/dist-packages/numpy/_core/fromnumeric.py:3824: RuntimeWarning: Mean of empty slice
  return _methods._mean(a, axis=axis, dtype=dtype,
/usr/local/lib/python3.12/dist-packages/numpy/_core/_methods.py:134: RuntimeWarning: invalid value encountered in divide
  ret = um.true_divide(

audio-1775054208.webm -> speakers=1
audio-1775054238.webm -> speakers=1
audio-1775054268.webm -> speakers=1
audio-1775054298.webm -> speakers=2
audio-1775054328.webm -> speakers=1
audio-1775054357.webm -> speakers=0
audio-1775054358.webm -> speakers=1
audio-1775054387.webm -> speakers=0
audio-1775054388.webm -> speakers=1
audio-1775054418.webm -> speakers=1
audio-1775054448.webm -> speakers=1
audio-1775054478.webm -> speakers=1
audio-1775054508.webm -> speakers=1
audio-1775054538.webm -> speakers=1
audio-1775054568.webm -> speakers=1
audio-1775054598.webm -> speakers=1
audio-1775054627.webm -> speakers=0
audio-1775054628.webm -> speakers=0
audio-1775054658.webm -> speakers=1
audio-1775054688.webm -> speakers=1
audio-1775054718.webm -> speakers=1
audio-1775054748.webm -> speakers=1
audio-1775054778.webm -> speakers=1
audio-1775054808.webm -> speakers=1
audio-1775054838.webm -> speakers=1
audio-1775054868.webm -> speakers=1
audio-1775054898.webm -> speakers=1
audio-1775054928.webm -> speakers=1
audio-1775054958.webm -> speakers=1
audio-1775054988 (1).webm -> speakers=0
audio-1775054988.webm -> speakers=1
audio-1775055018.webm -> speakers=1
audio-1775055048.webm -> speakers=1
audio-1775055077.webm -> speakers=0
audio-1775055078.webm -> speakers=1
audio-1775055107.webm -> speakers=0
audio-1775055108.webm -> speakers=0
audio-1775055138.webm -> speakers=0
audio-1775055198.webm -> speakers=0
audio-1775055258.webm -> speakers=0
audio-1775055317.webm -> speakers=0
audio-1775055347.webm -> speakers=0
audio-1775055377.webm -> speakers=0
audio-1775055407.webm -> speakers=0
audio-1775055437.webm -> speakers=0
audio-1775055467.webm -> speakers=0
audio-1775055497.webm -> speakers=0
audio-1775055587.webm -> speakers=0
audio-1775055677.webm -> speakers=0
audio-1775055707.webm -> speakers=0
audio-1775055737.webm -> speakers=0
audio-1775055887.webm -> speakers=0
audio-1775055947.webm -> speakers=0
audio-1775056127.webm -> speakers=0
audio-1775056217.webm -> speakers=0
audio-1775056247.webm -> speakers=0
audio-1775056337.webm -> speakers=0
audio-1775056367.webm -> speakers=0
audio-1775056487.webm -> speakers=0

In [ ]:
df = pd.DataFrame(results)

if df.empty:
    print("No results were created.")
else:
    df.to_csv("final_output.csv", index=False)
    print("Saved as final_output.csv")
    display(df.head(15))

Saved as final_output.csv

,file_name,duration,model_name,device_used,number_of_speakers,processing_time_sec,human_verification_speaker
0,audio-1775052030.webm,28.92,SileroVAD + Pyannote,cuda,1,1.82,None
1,audio-1775052060.webm,28.98,SileroVAD + Pyannote,cuda,0,0.66,None
2,audio-1775052090.webm,28.98,SileroVAD + Pyannote,cuda,0,0.69,None
3,audio-1775052120.webm,28.98,SileroVAD + Pyannote,cuda,1,1.15,None
4,audio-1775052150.webm,28.98,SileroVAD + Pyannote,cuda,1,0.98,None
5,audio-1775052180.webm,28.98,SileroVAD + Pyannote,cuda,1,1.21,None
6,audio-1775052210.webm,28.98,SileroVAD + Pyannote,cuda,1,0.79,None
7,audio-1775052240.webm,28.98,SileroVAD + Pyannote,cuda,1,1.04,None
8,audio-1775052270.webm,28.98,SileroVAD + Pyannote,cuda,1,1.07,None
9,audio-1775052300.webm,28.98,SileroVAD + Pyannote,cuda,1,1.12,None
10,audio-1775052330.webm,28.98,SileroVAD + Pyannote,cuda,1,0.97,None
11,audio-1775052360.webm,28.98,SileroVAD + Pyannote,cuda,2,1.56,None
12,audio-1775052390.webm,28.98,SileroVAD + Pyannote,cuda,1,1.24,None
13,audio-1775052420.webm,28.98,SileroVAD + Pyannote,cuda,1,0.86,None
14,audio-1775052450.webm,28.98,SileroVAD + Pyannote,cuda,1,0.75,None

In [ ]:
human_labels = [1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

df["human_verification_speaker"] = None
df.loc[:len(human_labels)-1, "human_verification_speaker"] = human_labels

display(df.head(15))

,file_name,duration,model_name,device_used,number_of_speakers,processing_time_sec,human_verification_speaker
0,audio-1775052030.webm,28.92,SileroVAD + Pyannote,cuda,1,1.82,1
1,audio-1775052060.webm,28.98,SileroVAD + Pyannote,cuda,0,0.66,0
2,audio-1775052090.webm,28.98,SileroVAD + Pyannote,cuda,0,0.69,0
3,audio-1775052120.webm,28.98,SileroVAD + Pyannote,cuda,1,1.15,1
4,audio-1775052150.webm,28.98,SileroVAD + Pyannote,cuda,1,0.98,1
5,audio-1775052180.webm,28.98,SileroVAD + Pyannote,cuda,1,1.21,1
6,audio-1775052210.webm,28.98,SileroVAD + Pyannote,cuda,1,0.79,1
7,audio-1775052240.webm,28.98,SileroVAD + Pyannote,cuda,1,1.04,1
8,audio-1775052270.webm,28.98,SileroVAD + Pyannote,cuda,1,1.07,1
9,audio-1775052300.webm,28.98,SileroVAD + Pyannote,cuda,1,1.12,1
10,audio-1775052330.webm,28.98,SileroVAD + Pyannote,cuda,1,0.97,1
11,audio-1775052360.webm,28.98,SileroVAD + Pyannote,cuda,2,1.56,1
12,audio-1775052390.webm,28.98,SileroVAD + Pyannote,cuda,1,1.24,1
13,audio-1775052420.webm,28.98,SileroVAD + Pyannote,cuda,1,0.86,1
14,audio-1775052450.webm,28.98,SileroVAD + Pyannote,cuda,1,0.75,1

In [ ]:
# Create dataframe
df = pd.DataFrame(results)

if df.empty:
    print("No results were created.")

else:
    # Step 1: Save original output
    df.to_csv("final_output.csv", index=False)
    print("Saved as final_output.csv")

    # Step 2: Add human labels
    human_labels = [1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

    df["human_verification_speaker"] = None
    df.loc[:len(human_labels)-1, "human_verification_speaker"] = human_labels

    # Step 3: Calculate accuracy
    valid_df = df.dropna(subset=["human_verification_speaker", "number_of_speakers"])

    accuracy = (valid_df["number_of_speakers"] == valid_df["human_verification_speaker"]).mean() * 100
    mae = (valid_df["number_of_speakers"] - valid_df["human_verification_speaker"]).abs().mean()

    print("\nAccuracy:", round(accuracy, 2), "%")
    print("MAE:", round(mae, 2))

    print("\nCorrect Predictions:",
          (valid_df["number_of_speakers"] == valid_df["human_verification_speaker"]).sum())
    print("Total Checked:", len(valid_df))

    # Step 4: Save updated CSV
    df.to_csv("final_output_with_human_labels.csv", index=False)
    print("\nSaved as final_output_with_human_labels.csv")

    display(df.head(15))

Saved as final_output.csv

Accuracy: 93.33 %
MAE: 0.07

Correct Predictions: 14
Total Checked: 15

Saved as final_output_with_human_labels.csv

,file_name,duration,model_name,device_used,number_of_speakers,processing_time_sec,human_verification_speaker
0,audio-1775052030.webm,28.92,SileroVAD + Pyannote,cuda,1,1.82,1
1,audio-1775052060.webm,28.98,SileroVAD + Pyannote,cuda,0,0.66,0
2,audio-1775052090.webm,28.98,SileroVAD + Pyannote,cuda,0,0.69,0
3,audio-1775052120.webm,28.98,SileroVAD + Pyannote,cuda,1,1.15,1
4,audio-1775052150.webm,28.98,SileroVAD + Pyannote,cuda,1,0.98,1
5,audio-1775052180.webm,28.98,SileroVAD + Pyannote,cuda,1,1.21,1
6,audio-1775052210.webm,28.98,SileroVAD + Pyannote,cuda,1,0.79,1
7,audio-1775052240.webm,28.98,SileroVAD + Pyannote,cuda,1,1.04,1
8,audio-1775052270.webm,28.98,SileroVAD + Pyannote,cuda,1,1.07,1
9,audio-1775052300.webm,28.98,SileroVAD + Pyannote,cuda,1,1.12,1
10,audio-1775052330.webm,28.98,SileroVAD + Pyannote,cuda,1,0.97,1
11,audio-1775052360.webm,28.98,SileroVAD + Pyannote,cuda,2,1.56,1
12,audio-1775052390.webm,28.98,SileroVAD + Pyannote,cuda,1,1.24,1
13,audio-1775052420.webm,28.98,SileroVAD + Pyannote,cuda,1,0.86,1
14,audio-1775052450.webm,28.98,SileroVAD + Pyannote,cuda,1,0.75,1

In [ ]:
from google.colab import files
files.download("final_output_with_human_labels.csv")

In [ ]:
from google.colab import files
files.download("final_output.csv")